// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskesOfProjects.Data;

#nullable disable

namespace TaskesOfProjects.Migrations
{
    [DbContext(typeof(ProjectsContext))]
    [Migration("20221218061933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectsTaskes.Models.PrTask", b =>
                {
                    b.Property<int>("PrTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrTaskId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("enumTaskStatus")
                        .HasColumnType("int");

                    b.Property<int>("intPriorityTask")
                        .HasColumnType("int");

                    b.Property<string>("strDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strTaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PrTaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("PrTasks");
                });

            modelBuilder.Entity("ProjectsTaskes.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("dtCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("enumCurrentProjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("intPriorityProject")
                        .HasColumnType("int");

                    b.Property<string>("strProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectsTaskes.Models.PrTask", b =>
                {
                    b.HasOne("ProjectsTaskes.Models.Project", "Project")
                        .WithMany("PrTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsTaskes.Models.Project", b =>
                {
                    b.Navigation("PrTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
